- hosts: lab
  become: true
  tasks:
          - name: Add user
            user:
                name: random
                shell: /bin/zsh
                comment: random user
                groups: sudo,docker
                append: yes
                     
