- hosts: lab
  become: true
  tasks:
          - name: Install docker dependencies
            apt:
                pkg:
                    - apt-transport-https
                    - ca-certificates
                    - curl
                    - gnupg-agent
                    - software-properties-common

