- hosts: lab
  become: true
  tasks:
          - name: Add docker repo 
            apt_repository:
                    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
                    state: present
                    filename: docker 
